matrix:
  include:
    - language: scala
      scala:
        - 2.12.4
        - 2.11.8
      jdk:
        - oraclejdk8
      
      script: |
        sbt ++$TRAVIS_SCALA_VERSION clean test
      
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot/
    - language: java
